### ISSUE TITLE
cf login rejected

### ISSUE THREAD

**Issue by paulvi** [cloudfoundry-samples/cf-sample-app-spring#18]
I was unable to try out PCF
https://pivotal.io/platform/pcf-tutorials/getting-started-with-pivotal-cloud-foundry/introduction

as stopped on step 
https://pivotal.io/platform/pcf-tutorials/getting-started-with-pivotal-cloud-foundry/deploy-the-sample-app

impossible to login to PCF as login is just rejected 
(password is not asked)

```
$ cf login 
API endpoint: https://api.run.pivotal.io  
Email> [my company email is entered here]


Authenticating...               
Credentials were rejected, please try again.        
Authenticating...                                                                                          
Credentials were rejected, please try again.         
Authenticating...                             
Credentials were rejected, please try again.                                                                                                                                                                      API endpoint:   https://api.run.pivotal.io (API version: 2.134.0)         
Not logged in. Use 'cf login' to log in.  
FAILED          
Unable to authenticate.
```

Yes, it is not error of the code in this repository,
but as https://pivotal.io/platform Start Free Trial leads here.  

I think it would be nice if such issues can be answered in README on the website

**Comment by dmikusa** [comment]
FYI, that looks like the first known issue listed here -> https://github.com/cloudfoundry/cli#known-issues

**Comment by paulvi** [comment]
Indeed, that is https://github.com/cloudfoundry/cli/issues/171

works OK from `cmd`
