### ISSUE TITLE
cannot be cloned

### ISSUE THREAD

**Issue by timbuktuprincess** [cloudfoundry-samples/cf-sample-app-spring#7]
git.exe clone --progress --recursive -v "https://github.com/cloudfoundry-samples/cf-sample-app-spring.git" "F:\Dev\DCE\sourcecode\cf-sample\cf-sample-app-spring"

Cloning into 'F:\Dev\DCE\sourcecode\cf-sample\cf-sample-app-spring'...
fatal: unable to access 'https://github.com/cloudfoundry-samples/cf-sample-app-spring.git/': SSL certificate problem: unable to get local issuer certificate

Could you please share the certificate.
Thanks

**Comment by scottfrederick** [comment]
@timbuktuprincess This error is coming from `git.exe` regarding the certificate from `https://github.com`. It's likely a problem with your local setup or your network access to `https://github.com`.
